CREATE TABLE IF NOT EXISTS Beacon
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	
	Address VARCHAR(17) NOT NULL UNIQUE,
	Name VARCHAR(20) NOT NULL UNIQUE,
	Description TEXT
);

CREATE TABLE IF NOT EXISTS Log
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	
	BeaconID INTEGER REFERENCES Beacon(ID),
	EnterArea TINYINT(1) NOT NULL,
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	TimeStamp LONG NOT NULL
);